name: generate_very_good_wearos_app

on:
  push:
    paths:
      - .github/workflows/generate_very_good_wearos_app.yaml
      - tool/generator/**
      - src/**
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dart-lang/setup-dart@v1

      - name: Install Dependencies
        working-directory: tool/generator
        run: dart pub get

      - name: Generate Template
        run: dart ./tool/generator/main.dart

      - name: Config Git User
        run: |
          git config user.name VGV Bot
          git config user.email vgvbot@users.noreply.github.com

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5.0.2
        with:
          base: main
          branch: chore/generate-very-good-wearos-app
          commit-message: "chore: generate very_good_wearos_app template"
          title: "chore: generate very_good_wearos_app template"
          body: Please squash and merge me!
          labels: bot
          author: VGV Bot <vgvbot@users.noreply.github.com>
          assignees: vgvbot
          reviewers: renancaraujo,wolfenrain
          committer: VGV Bot <vgvbot@users.noreply.github.com>
